apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-43od
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-43od
    app.kubernetes.io/part-of: ci1t-830-0001-app
  name: devfile-sample-43od
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-43od
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-43od
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0001-tenant/ci1t-830-0001-app/devfile-sample-43od@sha256:e621dae048c34b2ef0bdb5efd4794c79bbc3cca441ef1e5bf927ea6fb7571816
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
